# Generated by Django 5.2.6 on 2025-10-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_payments_options_alter_subscriptions_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("cash", "Наличные"), ("transfer", "Перевод на счет")],
                max_length=10,
                null=True,
            ),
        ),
    ]
