# Generated by Django 5.2.6 on 2025-10-17 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_alter_lesson_link_to_the_video"),
        ("users", "0005_alter_payments_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="paid_course",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="materials.course",
                verbose_name="Оплаченый курс",
            ),
            preserve_default=False,
        ),
    ]
