# Generated by Django 5.2.6 on 2025-10-18 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_payments_paid_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payments",
            name="price",
        ),
    ]
