# Generated by Django 5.2.6 on 2025-10-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_payments_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на оплату",
                max_length=600,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
    ]
