# Generated by Django 5.2.6 on 2025-10-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="link_to_the_video",
            field=models.URLField(
                blank=True,
                help_text="Вставте ссылку на видео",
                max_length=300,
                null=True,
                verbose_name="Ссылка на видео",
            ),
        ),
    ]
