# Generated by Django 5.2.6 on 2025-10-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_alter_lesson_link_to_the_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Цена курса/урока"
            ),
        ),
    ]
