# Generated by Django 5.2.7 on 2026-03-13 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_course_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["id"],
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
